# Generated by Django 5.0.2 on 2024-03-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaSeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
                ('peso', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juguetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripción', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ingrediente_estrella', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
