# Generated by Django 5.0.2 on 2024-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBuo', '0002_comidaseca_juguetes_recetas_delete_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
                ('peso', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ComidaSeca',
        ),
    ]
