# Generated by Django 5.0.2 on 2024-03-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBuo', '0003_comida_delete_comidaseca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juguetes',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
